# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: my-wrlist-ingress
#   namespace: my-namespace
#   annotations:
#     kubernetes.io/ingress.class: "alb"
#     alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:970547342771:certificate/18af3371-114a-43ca-87e4-f7328d131f67
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: ip
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
#     alb.ingress.kubernetes.io/group.name: "backend-api"  
#     alb.ingress.kubernetes.io/enable-cors: 'true'
#     alb.ingress.kubernetes.io/healthcheck-path: "/my/writing/test"
# spec:
#   ingressClassName: alb
#   rules:
#   - host: iteamoa-api.brynnpark.cloud
#     http:
#       paths:
#       - path: /my/writing
#         pathType: Prefix
#         backend:
#           service:
#             name: my-wrlist-service
#             port:
#               number: 80

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mypage-ingress
  namespace: mypage-namespace
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx 
  rules:
    - host: api-iteamoa.brynnpark.cloud
      http:
        paths:
        - path: /my/writing
          pathType: Prefix
          backend:
            service:
              name: mypage-service
              port:
                number: 80
        - path: /my/temp
          pathType: Prefix
          backend:
            service:
              name: mypage-service
              port:
                number: 80
        - path: /my/like
          pathType: Prefix
          backend:
            service:
              name: mypage-service
              port:
                number: 80