name: CI - Mypage Service

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI  # 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
    
      - name: Build JAR file
        run: ./gradlew clean build
    
      - name: Build Docker image
        run: |
            docker build \
            --build-arg AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} \
            --build-arg AWS_TABLE=${{ secrets.AWS_TABLE }} \
            --build-arg AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --build-arg AWS_SECRET_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/iteamoa/my-wrlist:${SHORT_SHA} .
      
      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/iteamoa/my-wrlist:${SHORT_SHA}
        
      - name: Update deployment.yaml with new image tag
        run: |
          yq e -i '.spec.template.spec.containers[0].image = "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/iteamoa/my-wrlist:'"${SHORT_SHA}"'"' k8s/my-wrlist-service-deployment.yaml
        
      - name: Commit and push updated deployment
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add k8s/my-wrlist-service-deployment.yaml
          git commit -m "Update mypage image to ${SHORT_SHA}" || echo "No changes to commit"
          git push